# -*- coding: utf-8 -*-
"""medical prescription.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QevkXwxgBHMwA1GAiwl79VnA9m_JfEEc
"""

# ================================================================
#  AI MEDICAL PRESCRIPTION VERIFICATION - GRANITE 3.3 2B VERSION
#  Single-cell code for Google Colab (GPU required)
# ================================================================

# ----------------------------
# Install Dependencies
# ----------------------------
!pip install --quiet transformers accelerate gradio sentencepiece safetensors evaluate
!pip install --quiet pillow pytesseract regex
!apt-get update -qq && apt-get install -y -qq tesseract-ocr

# ----------------------------
# Imports
# ----------------------------
import torch, re, json
from PIL import Image
import pytesseract
import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Running on:", device)

# ----------------------------
# Load IBM Granite 3.3 2B Instruct
# ----------------------------
MODEL_ID = "ibm-granite/granite-3.3-2b-instruct"

print("Loading Granite 3.3 2B ... please wait 1–2 minutes...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True
)

llm = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    temperature=0.0,
    do_sample=False
)

print("Granite 3.3 2B Loaded Successfully ✔")

# ================================================================
# SAMPLE DRUG DATABASE (expand later)
# ================================================================
DRUG_DB = {
    "paracetamol": {"generic": "paracetamol", "brand": ["crocin","calpol"], "min": 325, "max": 1000},
    "amoxicillin": {"generic": "amoxicillin", "brand": ["amoxil"], "min": 250, "max": 2000},
    "metformin": {"generic": "metformin", "brand": ["glucophage"], "min": 500, "max": 2000},
    "ibuprofen": {"generic": "ibuprofen", "brand": ["brufen","advil"], "min": 200, "max": 800}
}

INTERACTIONS = {
    ("warfarin","ibuprofen"): "High risk of bleeding (NSAID + anticoagulant)",
    ("metformin","contrast"): "Moderate risk: lactic acidosis with contrast dye"
}

# ----------------------------
# Utility Functions
# ----------------------------
def ocr_extract(img):
    try:
        return pytesseract.image_to_string(img)
    except:
        return ""

def match_drug(name):
    name = name.lower().strip()

    if name in DRUG_DB:
        return DRUG_DB[name]

    for k, v in DRUG_DB.items():
        if name in v["brand"]:
            return v
    return None

def extract_dose(text):
    m = re.search(r"(\d+)\s*(mg|g)", text.lower())
    if not m:
        return None
    dose = float(m.group(1))
    unit = m.group(2)
    if unit == "g":
        dose *= 1000
    return dose

# ================================================================
# MAIN VERIFICATION FUNCTION
# ================================================================
def verify(pres_image, pres_text, patient_info, allergies, current_meds):

    # ---------------------------------
    # STEP 1 — Extract text
    # ---------------------------------
    if pres_image is not None and (not pres_text or pres_text.strip() == ""):
        img = Image.fromarray(pres_image)
        pres_text = ocr_extract(img)

    if not pres_text.strip():
        return "❌ No prescription text found. Upload or type.", {}

    # ---------------------------------
    # STEP 2 — Drug parsing (simple prototype)
    # ---------------------------------
    lines = pres_text.split("\n")
    detected = []

    for line in lines:
        tokens = line.lower().split()
        if len(tokens)==0: continue

        drug_guess = tokens[0]
        drug_info = match_drug(drug_guess)
        dose = extract_dose(line)

        if drug_info:
            # Dose Check
            if dose is None:
                dose_flag = "Dose not detected"
            elif drug_info["min"] <= dose <= drug_info["max"]:
                dose_flag = "Dose in safe range"
            else:
                dose_flag = f"Dose OUTSIDE safe range ({drug_info['min']}–{drug_info['max']}mg)"

            detected.append({
                "raw": line,
                "drug": drug_info["generic"],
                "dose_mg": dose,
                "dose_check": dose_flag
            })

    # ---------------------------------
    # STEP 3 — Interaction Check
    # ---------------------------------
    drug_names = [d["drug"] for d in detected]
    interaction_msgs = []
    for d1 in drug_names:
        for d2 in drug_names:
            if d1 == d2: continue
            pair = tuple(sorted([d1,d2]))
            if pair in INTERACTIONS:
                interaction_msgs.append(INTERACTIONS[pair])

    # ---------------------------------
    # STEP 4 — LLM Summary using Granite
    # ---------------------------------
    prompt = f"""
You are an AI medical prescription verification system.
Summarize the following prescription in a clear and professional way.

Prescription:
{pres_text}

Detected Drugs:
{json.dumps(detected, indent=2)}

Interactions:
{interaction_msgs}

Write:
1. Drug validation summary
2. Dose safety notes
3. Interaction warnings
4. Completeness check (patient details + prescriber details)
"""

    summary = llm(prompt)[0]["generated_text"]

    # ---------------------------------
    # Return results
    # ---------------------------------
    final_report = "==== AI PRESCRIPTION VALIDATION ====\n\n"
    final_report += summary

    return final_report, {
        "drugs_detected": detected,
        "interactions": interaction_msgs,
        "summary": summary
    }

# ================================================================
# GRADIO UI
# ================================================================
with gr.Blocks() as demo:
    gr.Markdown("## 🧠 AI Medical Prescription Verification — Granite 3.3 2B")

    with gr.Row():
        img = gr.Image(label="Upload Prescription Image (optional)")
        txt = gr.Textbox(label="Paste Prescription Text (optional)", lines=8)

    patient = gr.Textbox(label="Patient Info (optional)")
    allergy = gr.Textbox(label="Allergies (comma-separated)")
    meds = gr.Textbox(label="Current Medications (comma-separated)")

    btn = gr.Button("VERIFY")
    out_report = gr.Textbox(label="Verification Report", lines=20)
    out_json = gr.JSON(label="Structured Output")

    btn.click(
        verify,
        inputs=[img, txt, patient, allergy, meds],
        outputs=[out_report, out_json]
    )

demo.launch(share=True)
# ================================
# AI Medical Prescription Verification App
# Using IBM Granite 3.3 2B Instruct + Gradio
# Single-cell Working Version (GPU Required)
# ================================

!pip install transformers accelerate gradio huggingface_hub -q

import gradio as gr
import json
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# =====================================================
# LOAD IBM GRANITE 3.3 2B INSTRUCT FROM HUGGINGFACE
# =====================================================
model_id = "ibm-granite/granite-3.3-2b-instruct"

print("Loading IBM Granite model... (This may take 1–2 minutes)")

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",      # <<< FIXED — only device_map, no device parameter
    torch_dtype="auto"
)

llm = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=300,
    temperature=0.2
)

# =====================================================
# MOCK DATABASES (Replace with real ones if needed)
# =====================================================

drug_database = {
    "paracetamol": {"min": 250, "max": 1000},
    "amoxicillin": {"min": 250, "max": 875},
    "ibuprofen": {"min": 200, "max": 800}
}

drug_interactions = {
    ("ibuprofen", "aspirin"): "High risk of bleeding",
    ("amoxicillin", "methotrexate"): "Increases methotrexate toxicity"
}

allergies = ["penicillin", "sulfa"]

# =====================================================
# AI CHECKER FUNCTION
# =====================================================

def verify_prescription(prescription_text):

    # Format prompt for Granite 3.3
    prompt = f"""
You are an AI Medical Prescription Verification System.
Analyze the following prescription and return the results in JSON:

Prescription:
{prescription_text}

Check the following:
1. DRUG VALIDATION:
   - Verify that drug names exist in the known database.
   - Check whether the dosage is within safe limits.

2. SAFETY CHECKS:
   - Drug–drug interactions.
   - Allergy risks.

3. PRESCRIPTION COMPLETENESS:
   - Check if patient name, DOB, prescriber name, and license number are present.

Return the result ONLY in JSON with keys:
drug_validation, safety_checks, completeness_check.
"""

    ai_output = llm(prompt)[0]["generated_text"]

    # The model outputs the prompt + response → extract JSON part
    try:
        json_start = ai_output.index("{")
        json_end = ai_output.rindex("}") + 1
        ai_json = ai_output[json_start:json_end]
        result = json.loads(ai_json)
    except:
        result = {"error": "Could not parse AI output", "raw_output": ai_output}

    return result


# =====================================================
# GRADIO UI
# =====================================================

ui = gr.Interface(
    fn=verify_prescription,
    inputs=gr.Textbox(lines=10, label="Enter Prescription Text"),
    outputs=gr.JSON(label="AI Verification Result"),
    title="AI Medical Prescription Verification App",
    description="Powered by IBM Granite 3.3 2B Instruct"
)

ui.launch(share=True)